[package]
name = "virtual-shell"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
dgxlab-contracts.workspace = true
slurm-model.workspace = true
sim-core.workspace = true
virtual-fs.workspace = true
serde.workspace = true
thiserror.workspace = true
