[package]
name = "scenarios"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
dgxlab-contracts.workspace = true
slurm-model.workspace = true
sim-core.workspace = true
actors.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
